# Generated by Django 4.2 on 2023-04-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="forum_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=20, verbose_name="제목")),
                ("name", models.CharField(max_length=20, verbose_name="이름")),
                ("story", models.TextField(verbose_name="내용")),
            ],
            options={
                "verbose_name": "글쓴이",
                "verbose_name_plural": "글쓴이들",
                "ordering": ["name"],
            },
        ),
    ]
